services:
  app:
    build: .
    container_name: medipole_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/medipole
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - medipole_net

  db:
    image: postgres:15-alpine
    container_name: medipole_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medipole
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - medipole_net

  redis:
    image: redis:7-alpine
    container_name: medipole_redis
    ports:
      - "6379:6379"
    networks:
      - medipole_net

networks:
  medipole_net:
    driver: bridge

volumes:
  db_data: